MvcClient/Controllers/BasketController.cs
using Microsoft.AspNetCore.Mvc;
using MvcClient.Application;
using MvcClient.Dtos.Basket;
using MvcClient.Enums;
using MvcClient.Models.Basket;
using MvcClient.Models.Catalog;

namespace MvcClient.Controllers
{
    public class BasketController : Controller
    {

        private readonly IBasketService _basketService;
        private readonly ILogger<BasketController> _logger;
        private const string _basketState = "BasketState";
        private const string _name = "Name";
        private const string _isError = "IsError";

        public BasketController(IBasketService basketService, ILogger<BasketController> logger)
        {
            _basketService = basketService;
            _logger = logger;
        }

        public async Task<IActionResult> Index()
        {
            _logger.LogInformation("Basket Index call.");
            IEnumerable<BasketListModel> model;
            try
            {
                var filterTask = _basketService.Filter(new BasketFilterDto());
                if (TempData.ContainsKey(_basketState))
                {
                    ViewData[_basketState] = TempData[_basketState];
                    ViewData[_name] = TempData[_name];
                }
                model = await filterTask;
            }
            catch (HttpRequestException ex)
            {
                _logger.LogError("Error getting baskets with the following exception: " + ex.Message + Environment.NewLine +
                    ex.InnerException + Environment.NewLine +
                    ex.StackTrace, ex, this);
                model = new List<BasketListModel>();
                ViewData[_isError] = true;
            }
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> AddToBasket([FromForm] CatalogAddToBasketModel requestModel)
        {
            _logger.LogInformation("AddToBasket call for buyer {buyer}.", requestModel.Buyer);
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            await _basketService.AddToBasket(new CatalogAddToBasketDto(requestModel));
            TempData[_basketState] = BasketState.Added;
            TempData[_name] = requestModel.ProductName;
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Checkout([FromForm] BasketCheckoutRequest requestModel)
        {
            _logger.LogInformation("Basket Checkout call for buyer {buyer}.", requestModel.Buyer);
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            await _basketService.Checkout(new BasketCheckoutDto(requestModel));
            TempData[_name] = requestModel.Buyer;
            return RedirectToAction("Index", "Order");
        }

        public async Task<IActionResult> Delete(string buyer, Guid id)
        {
            _logger.LogInformation("Basket Delete call for buyer {buyer}.", buyer);
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            var basketDeleteDto = new BasketDeleteDto
            {
                Buyer = buyer,
                CacheId = id
            };
            TempData[_basketState] = BasketState.Deleted;
            TempData[_name] = buyer;
            await _basketService.Delete(basketDeleteDto);
            return RedirectToAction("Index");
        }
    }
}

MvcClient/Controllers/CatalogController.cs
using Microsoft.AspNetCore.Mvc;
using MvcClient.Application;
using MvcClient.Dtos.Catalog;
using MvcClient.Enums;
using MvcClient.Models.Basket;
using MvcClient.Models.Catalog;

namespace MvcClient.Controllers
{
    public class CatalogController : Controller
    {
        private readonly ICatalogService _catalogService;
        private readonly ILogger<CatalogController> _logger;
        private const string _catalogState = "CatalogState";
        private const string _catalogName = "CatalogName";
        private const string _isError = "IsError";

        public CatalogController(ICatalogService catalogService, ILogger<CatalogController> logger)
        {
            _catalogService = catalogService;
            _logger = logger;
        }

        public async Task<IActionResult> Index()
        {
            _logger.LogInformation("Catalog Index call.");
            IEnumerable<CatalogListModel> model;
            try
            {
                var filterTask = _catalogService.Filter(new CatalogFilterDto());
                if (TempData.ContainsKey(_catalogState))
                {
                    ViewData[_catalogState] = TempData[_catalogState];
                    ViewData[_catalogName] = TempData[_catalogName];
                }
                model = await filterTask;
            }
            catch (HttpRequestException ex)
            {
                _logger.LogError("Error getting catalogs with the following exception: " + ex.Message + Environment.NewLine +
                    ex.InnerException + Environment.NewLine +
                    ex.StackTrace, ex, this);
                model = new List<CatalogListModel>();
                ViewData[_isError] = true;
            }
            return View(model);
        }

        [HttpGet]
        public IActionResult Create()
        {
            _logger.LogInformation("Catalog Create Get call.");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([FromForm] CatalogCreateDto catalogCreateDto)
        {
            _logger.LogInformation("Catalog Create Post call.");
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            await _catalogService.Create(catalogCreateDto);
            TempData[_catalogState] = CatalogState.Created;
            TempData[_catalogName] = catalogCreateDto.Name;
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Details([FromRoute] Guid id)
        {
            _logger.LogInformation("Catalog Details call.");
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            var catalogDetailsDto = new CatalogDetailsDto
            {
                Id = id
            };
            return View(await _catalogService.Details(catalogDetailsDto));
        }

        [HttpGet]
        public async Task<IActionResult> Edit([FromRoute] Guid id)
        {
            _logger.LogInformation("Catalog Edit Get call.");
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            var catalogDetailsDto = new CatalogDetailsDto
            {
                Id = id
            };
            var catalogEditDto = new CatalogEditDto(await _catalogService.Details(catalogDetailsDto));
            return View(catalogEditDto);
        }

        [HttpPost]
        public async Task<IActionResult> Edit([FromForm] CatalogEditDto catalogEditDto)
        {
            _logger.LogInformation("Catalog Edit Post call.");
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            await _catalogService.Update(catalogEditDto);
            TempData[_catalogState] = CatalogState.Edited;
            TempData[_catalogName] = catalogEditDto.Name;
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(Guid id)
        {
            _logger.LogInformation("Catalog Delete {guid} call.", id);
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            var catalogDeleteDto = new CatalogDeleteDto
            {
                Id = id
            };
            string name = await _catalogService.Delete(catalogDeleteDto);
            TempData[_catalogState] = CatalogState.Deleted;
            TempData[_catalogName] = name;
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> AddToBasket([FromRoute] Guid id)
        {
            _logger.LogInformation("Catalog Get Add {guid} ToBasket call.", id);
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            var catalogDetailsDto = new CatalogDetailsDto
            {
                Id = id
            };
            var catalogAddToBasketModel = new CatalogAddToBasketModel(await _catalogService.Details(catalogDetailsDto));
            return View(catalogAddToBasketModel);
        }
    }
}

MvcClient/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using MvcClient.Application;
using MvcClient.Dtos.Order;
using MvcClient.Models.Order;

namespace MvcClient.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrderService _orderService;
        private readonly ILogger<OrderController> _logger;
        private const string _isDelete = "IsDelete";
        private const string _name = "Name";
        private const string _isError = "IsError";

        public OrderController(IOrderService orderService, ILogger<OrderController> logger)
        {
            _orderService = orderService;
            _logger = logger;
        }

        public async Task<IActionResult> Index()
        {
            _logger.LogInformation("Order Index call.");
            if (TempData.ContainsKey(_isDelete))
            {
                ViewData[_isDelete] = TempData[_isDelete];
            }
            else if (TempData.ContainsKey(_name))
            {
                ViewData[_name] = TempData[_name];
            }
            IEnumerable<OrderModel> orderModels;
            try
            {
                orderModels = await _orderService.Filter(new OrderFilterDto());
            }
            catch (HttpRequestException ex)
            {
                _logger.LogError("Error getting orders with the following exception: " + ex.Message + Environment.NewLine +
                    ex.InnerException + Environment.NewLine +
                    ex.StackTrace, ex, this);
                orderModels = new List<OrderModel>();
                ViewData[_isError] = true;
            }
            return View(orderModels);
        }

        public async Task<IActionResult> Details([FromRoute] Guid id)
        {
            _logger.LogInformation("Order Details {guid} call.", id);
            var orderDetailDto = new OrderDetailDto {
                Id = id
            };
            return View(await _orderService.Details(orderDetailDto));
        }

        public async Task<IActionResult> Delete()
        {
            _logger.LogInformation("Order Delete call.");
            await _orderService.Delete();
            TempData[_isDelete] = true;
            return RedirectToAction("Index");
        }
    }
}

MvcClient/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Authentication
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcClient</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcClient.styles.css" asp-append-version="true" />
    <base href="~/" />
    <component type="typeof(Microsoft.AspNetCore.Components.Web.HeadOutlet)"
               render-mode="ServerPrerendered" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcClient</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.Claims.Count() > 0)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Catalog" asp-action="Index">Catalog</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Basket" asp-action="Index">Basket</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="Index">Order</a>
                            </li>
                        }
                        <li class="nav-item flex-grow-1">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if (User.Claims.Count() > 0)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Logout">Logout</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MvcClient - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="_framework/blazor.server.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
     <persist-component-state />
</body>
</html>